---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
  - name: code
  - name: ci

outputs:
  - name: coverage

run:
  path: ci/tasks/run-unit-tests