---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
  - name: code
    path: go/src/github.com/lflux/concourse-coverage
  - name: ci

outputs:
  - name: coverage

run:
  path: ci/tasks/run-unit-tests