---
resources:
- name: ci
  type: git
  source:
    uri: https://github.com/lflux/concourse-onboarding.git
    branch: master
jobs:
- name: hello-world
  plan:
  - get: ci
    trigger: true
  - task: say-hello
    file: ci/tasks/say-hello.yml
    params:
      SAY: hello